name: Snyk Test

on:
    push: 
        branches:
            - main
    pull_request:

jobs: 
    snyk-scan:
        runs-on: ubuntu-22.04
        steps:
            - name: Check out code
              uses: actions/checkout@v3
         
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Snyk CLI
              run: npm install -g snyk

            - name: Authenticate Snyk
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              run: snyk auth $SNYK_TOKEN
      
            - name: Run Snyk Test
              run: snyk test 
        
            - name: Monitor Snyk Results
              run: snyk monitor
